In [ ]:
# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data_yelp = pd.read_csv('yelp_labelled.txt', sep='\t',header=None)
data_amazon = pd.read_csv('amazon_cells_labelled.txt', sep='\t',header=None)
data_imdb = pd.read_csv('imdb_labelled.txt', sep='\t',header=None)

In [ ]:
data_yelp

0  1
0                             Wow... Loved this place.  1
1                                   Crust is not good.  0
2            Not tasty and the texture was just nasty.  0
3    Stopped by during the late May bank holiday of...  1
4    The selection on the menu was great and so wer...  1
..                                                 ... ..
995  I think food should have flavor and texture an...  0
996                           Appetite instantly gone.  0
997  Overall I was not impressed and would not go b...  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

[1000 rows x 2 columns]

In [ ]:
data_amazon

0  1
0    So there is no way for me to plug it in here i...  0
1                          Good case, Excellent value.  1
2                               Great for the jawbone.  1
3    Tied to charger for conversations lasting more...  0
4                                    The mic is great.  1
..                                                 ... ..
995  The screen does get smudged easily because it ...  0
996  What a piece of junk.. I lose more calls on th...  0
997                       Item Does Not Match Picture.  0
998  The only thing that disappoint me is the infra...  0
999  You can not answer calls with the unit, never ...  0

[1000 rows x 2 columns]

In [ ]:
data_imdb

0  1
0    A very, very, very slow-moving, aimless movie ...  0
1    Not sure who was more lost - the flat characte...  0
2    Attempting artiness with black & white and cle...  0
3         Very little music or anything to speak of.    0
4    The best scene in the movie was when Gerardo i...  1
..                                                 ... ..
743  I just got bored watching Jessice Lange take h...  0
744  Unfortunately, any virtue in this film's produ...  0
745                   In a word, it is embarrassing.    0
746                               Exceptionally bad!    0
747  All in all its an insult to one's intelligence...  0

[748 rows x 2 columns]

In [ ]:
data = data_imdb.append([data_yelp, data_amazon], ignore_index=True)
data

<ipython-input-49-d052b1d5c4d7>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data_imdb.append([data_yelp, data_amazon], ignore_index=True)


0  1
0     A very, very, very slow-moving, aimless movie ...  0
1     Not sure who was more lost - the flat characte...  0
2     Attempting artiness with black & white and cle...  0
3          Very little music or anything to speak of.    0
4     The best scene in the movie was when Gerardo i...  1
...                                                 ... ..
2743  The screen does get smudged easily because it ...  0
2744  What a piece of junk.. I lose more calls on th...  0
2745                       Item Does Not Match Picture.  0
2746  The only thing that disappoint me is the infra...  0
2747  You can not answer calls with the unit, never ...  0

[2748 rows x 2 columns]

In [ ]:
columan_name = ['Review', 'Sentiment']

In [ ]:
data.columns = ['Review', 'Sentiment']

In [ ]:
data.columns

Index(['Review', 'Sentiment'], dtype='object')

In [ ]:
data.Review.value_counts()

Not recommended.                                                                                                      2
Great phone!.                                                                                                         2
10/10                                                                                                                 2
Great Phone.                                                                                                          2
I won't be back.                                                                                                      2
                                                                                                                     ..
So don't go there if you are looking for good food...                                                                 1
I've never been treated so bad.                                                                                       1
Bacon is hella salty.                   

In [ ]:
data.Sentiment.value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [ ]:
# check for null values
data.isnull().sum()

# no null values in the data

Review       0
Sentiment    0
dtype: int64

In [ ]:
x = data['Review']
y = data['Sentiment']

In [ ]:
# Cleaning Data

# here we will remove stopwords, punctuations
# as well as we will apply lemmatization

In [ ]:
# Create a function to clean data

import string
punct = string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
stopwords = list(STOP_WORDS) # list of stopwords

In [ ]:
stopwords

['another',
 'name',
 'whence',
 'alone',
 'there',
 'become',
 'every',
 'himself',
 'hereafter',
 'you',
 'seemed',
 'ten',
 'wherein',
 'hereby',
 'even',
 'much',
 'than',
 'off',
 'against',
 'regarding',
 'almost',
 'herein',
 'thereupon',
 'whereafter',
 'always',
 'themselves',
 'serious',
 'side',
 'sometime',
 'few',
 'indeed',
 'she',
 'using',
 'one',
 'eleven',
 'many',
 'whereupon',
 'its',
 'from',
 'such',
 'out',
 'something',
 'perhaps',
 'call',
 'most',
 "'s",
 'around',
 'could',
 'should',
 'down',
 "'re",
 'only',
 'put',
 'afterwards',
 'though',
 '’re',
 'before',
 'get',
 '‘d',
 'what',
 'here',
 'between',
 'ca',
 'yourselves',
 'toward',
 'enough',
 'seeming',
 'whole',
 'anyhow',
 'which',
 'else',
 'becoming',
 'cannot',
 'others',
 'would',
 'give',
 'it',
 'and',
 'please',
 'everything',
 'three',
 'anything',
 'formerly',
 'an',
 'those',
 'although',
 'mostly',
 'he',
 'by',
 'seem',
 'of',
 'several',
 'someone',
 'any',
 'show',
 'how',
 'why',
 'wh

In [ ]:
# creating a function for data cleaning

import spacy

nlp = spacy.load('en_core_web_sm')

def text_data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = [] # list of tokens
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)

  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens

In [ ]:
# if root form of that word is not pronoun then it is going to convert that into lower form
# and if that word is a proper noun, then we are directly taking lower form, because there is no lemma for proper noun

In [ ]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")
# stopwords and punctuations removed

['hello', 'beautiful', 'day', 'outside']

In [ ]:
## Vectorization Feature Engineering (TF-IDF)

from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [ ]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)
# tokenizer=text_data_cleaning, tokenization will be done according to this function

In [ ]:
classifier = LinearSVC()

In [ ]:
# Train the model
## Splitting the dataset into the Train and Test set

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
x_train.shape, x_test.shape
# 2198 samples in training dataset and 550 in test dataset

((2198,), (550,))

In [ ]:
clf = Pipeline([('tfidf',tfidf), ('clf',classifier)])
# it will first do vectorization and then it will do classification

In [ ]:
clf.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x7e0eff839b40>)),
                ('clf', LinearSVC())])

In [ ]:
# 4) Predict the Test set results

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
# confusion_matrix
confusion_matrix(y_test, y_pred)

array([[204,  51],
       [ 58, 237]])

In [ ]:
# classification_report
print(classification_report(y_test, y_pred))
# we are getting almost 77% accuracy

              precision    recall  f1-score   support

           0       0.78      0.80      0.79       255
           1       0.82      0.80      0.81       295

    accuracy                           0.80       550
   macro avg       0.80      0.80      0.80       550
weighted avg       0.80      0.80      0.80       550



In [ ]:
accuracy_score(y_test, y_pred)
# 76% accuracy

0.8018181818181818

In [ ]:
clf.predict(["Wow, I am learning Natural Language Processing in fun fashion!"])
# output is 1, that means review is positive

array([1])

In [ ]:
clf.predict(["It's hard to learn new things!"])
# output is 0, that means review is Negative

array([0])